// Code generated by protoc-gen-go. DO NOT EDIT.
// source: text1.proto

package text1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//熊猫 发送的消息
type PandaRequest struct {
	//姓名
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	//身高
	Shengao int32 `protobuf:"varint,2,opt,name=shengao,proto3" json:"shengao,omitempty"`
	//体重
	Tizhong              []int32  `protobuf:"varint,3,rep,packed,name=tizhong,proto3" json:"tizhong,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PandaRequest) Reset()         { *m = PandaRequest{} }
func (m *PandaRequest) String() string { return proto.CompactTextString(m) }
func (*PandaRequest) ProtoMessage()    {}
func (*PandaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c52d883d2746fb54, []int{0}
}

func (m *PandaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PandaRequest.Unmarshal(m, b)
}
func (m *PandaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PandaRequest.Marshal(b, m, deterministic)
}
func (m *PandaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PandaRequest.Merge(m, src)
}
func (m *PandaRequest) XXX_Size() int {
	return xxx_messageInfo_PandaRequest.Size(m)
}
func (m *PandaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PandaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PandaRequest proto.InternalMessageInfo

func (m *PandaRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PandaRequest) GetShengao() int32 {
	if m != nil {
		return m.Shengao
	}
	return 0
}

func (m *PandaRequest) GetTizhong() []int32 {
	if m != nil {
		return m.Tizhong
	}
	return nil
}

//熊猫的返回消息
type PandaResponse struct {
	//错误号
	Error int32 `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	//错误信息
	Ermessage            string   `protobuf:"bytes,2,opt,name=ermessage,proto3" json:"ermessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PandaResponse) Reset()         { *m = PandaResponse{} }
func (m *PandaResponse) String() string { return proto.CompactTextString(m) }
func (*PandaResponse) ProtoMessage()    {}
func (*PandaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c52d883d2746fb54, []int{1}
}

func (m *PandaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PandaResponse.Unmarshal(m, b)
}
func (m *PandaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PandaResponse.Marshal(b, m, deterministic)
}
func (m *PandaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PandaResponse.Merge(m, src)
}
func (m *PandaResponse) XXX_Size() int {
	return xxx_messageInfo_PandaResponse.Size(m)
}
func (m *PandaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PandaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PandaResponse proto.InternalMessageInfo

func (m *PandaResponse) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *PandaResponse) GetErmessage() string {
	if m != nil {
		return m.Ermessage
	}
	return ""
}

func init() {
	proto.RegisterType((*PandaRequest)(nil), "PandaRequest")
	proto.RegisterType((*PandaResponse)(nil), "PandaResponse")
}

func init() { proto.RegisterFile("text1.proto", fileDescriptor_c52d883d2746fb54) }

var fileDescriptor_c52d883d2746fb54 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x49, 0xad, 0x28,
	0x31, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x0a, 0xe3, 0xe2, 0x09, 0x48, 0xcc, 0x4b, 0x49,
	0x0c, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0x24, 0xb8, 0xd8, 0x8b, 0x33, 0x52, 0xf3,
	0xd2, 0x13, 0xf3, 0x25, 0x98, 0x14, 0x18, 0x35, 0x58, 0x83, 0x60, 0x5c, 0x90, 0x4c, 0x49, 0x66,
	0x55, 0x46, 0x7e, 0x5e, 0xba, 0x04, 0xb3, 0x02, 0x33, 0x48, 0x06, 0xca, 0x55, 0x72, 0xe6, 0xe2,
	0x85, 0x9a, 0x5b, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x24, 0xc2, 0xc5, 0x9a, 0x5a, 0x54, 0x94,
	0x5f, 0x04, 0x36, 0x99, 0x35, 0x08, 0xc2, 0x11, 0x92, 0xe1, 0xe2, 0x4c, 0x2d, 0xca, 0x4d, 0x2d,
	0x2e, 0x4e, 0x4c, 0x4f, 0x05, 0x1b, 0xce, 0x19, 0x84, 0x10, 0x48, 0x62, 0x03, 0xbb, 0xd1, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x4a, 0x5d, 0x2e, 0xb2, 0x00, 0x00, 0x00,
}
